### ISSUE TITLE
Consider support for "serverless"/"chalice" in a way

### ISSUE THREAD

**Issue by DeviaVir** [pebble/spacel-provision#32]
[serverless](https://serverless.com/) (for node.js apps) and [chalice](https://github.com/awslabs/chalice) (for python apps) provide mostly the same features, we might be able to support both by executing certain startup scripts, not rolling out any infrastructure and by setting environment variables in dynamodb (so lambda can access them there).

**Comment by thepwagner** [comment]
Are other folks doing configuration-in-dynamo? Or just an idea?
I'm wondering about baking environment variables into the uploaded code to avoid the ~15-50ms cost of fetching config for each invocation. (TODO: should that include passwords too? they're secrets, but even _slower_ to access)

How does aliasing/HTTPS work? (Didn't see anything for CNAME `foo-service.acme.com` while skimming both project docs).


The biggest blocker I'm seeing here is the decision to let `spacel-agent` build environment variables at startup time ( https://github.com/pebble/spacel-agent/pull/25 ): environment dumping to codesnippet/dynamo is easier if this logic is in `spacel-provision`.

**Comment by DeviaVir** [comment]
Just a possible path, I can imagine `spacel-provision` eventually supporting many methods to achieve the same.

Aliasing/HTTPS support is, sadly enough, bad. You have to jump through some very silly hoops to achieve it, considering it is already running on CloudFront. I'd vote to do it manually until AWS makes this better (assuming that if we were to automate the hoops AWS would make it easier by the time we had this ready).

True, but it would be even nicer if these methods could co-exist?
