### ISSUE TITLE
Allow deploys without NAT gateway

### ISSUE THREAD

**Issue by DeviaVir** [pebble/spacel-provision#45]

**Comment by DeviaVir** [comment]
@thepwagner initial idea for this is to not make it a customizable thing, I think it would be pretty rad if we can detect if any of our services are using the private subnets and if so create the nat gateway _only then_ (and saving a good $30 for people that just want to push a docker into the cloud and watch what happens).

Roadblock I hit was trying to figure out if any services are using private subnets via the https://github.com/pebble/spacel-provision/blob/master/src/spacel/provision/template/vpc.py template. If this makes sense at all, I'd suggest making the nat gateway (and other private subnet things) a separate template that is only called on if we detected a service that makes use of a private subnet. Might get fuzzy multiregion, but should be doable.

Thoughts?

**Comment by thepwagner** [comment]
You could just pass the `SpaceApp` into the `OrbitFactory`, into the... (continued).
The path is possible, but it breaks down the neat abstraction layer that the (shared) `Orbit` is prepared without consideration of which particular `SpaceApp` is being deployed.

There shouldn't be a "global list of `SpaceApp`s" anywhere either, so you'd need to get clever to leave a breadcrumb in CF that NAT is needed by _an_ application: either a template that gets created as suggested, or a CF `Parameter` that gets `UsePreviousValue`-ed unless it's explicitly set to true.


I think detection is _cool_, but a flag is probably the stronger feature:
* we want to encourage best practices; double-bagging your instances (not internet-routable _and_ in a paranoid security group) when possible is one of those
* `orbit.json` is likely static, owned by an operations-y team that cares about security/sdlc, `app.json` is likely volatile, owned by a development team that just wants to ship `app`+updates.

That makes me think `I know what I'm doing and don't want to pay for a NAT gateway` is something that `orbit.json` should set explicitly, and the App provisioning should adjust defaults according to that decision (i.e. `availability` default becomes `public`; if the app requested `private` then we error out and tell them to adjust `orbit.json` or stop being so picky).

That also keeps the `Orbit`->`SpaceApp` abstraction flow neatly in check.



Other fuzzy bit with detection is if a private Cache/RDS instance should trigger a NAT gateway. I have no idea atm: maybe we shouldn't even give those subnets a route to the NAT GW? even less chance of exfiltration!

**Comment by DeviaVir** [comment]
@thepwagner sound reasoning, agreed. Will pick this up first as the scope became a lot smaller.
