### ISSUE TITLE
Route53: Healthchecks and weighted (multi-region) setup

### ISSUE THREAD

**Issue by DeviaVir** [pebble/spacel-provision#61]
Discussion in https://github.com/pebble/spacel-provision/pull/59#discussion_r88238694

**Comment by thepwagner** [comment]
I think multi-region is free: https://github.com/pebble/spacel-provision/blob/c1ca1a8b87d4f6674c937eaf71a6f7b737bd6ee2/src/spacel/cloudformation/elb-service.template#L244

I only tested that pattern with early ELB setups though.
